swagger: "2.0"
basePath: /claim/v1
x-gw-combine:
- ext.claim.v1.claim_auto_ext-1.0
- ext.claim.v1.claim_property_ext-1.0
- ext.claim.v1.claim_ext-1.0
x-gw-schema-import:
  claims: ext.claim.v1.claim_combined_ext-1.0
paths: {}